### ISSUE TITLE
Add Unique Reusable Rating Component

### ISSUE THREAD

**Issue by hasin-zaman** [hasin-zaman/UIlex#3]
UIlex is a community-driven platform where developers can share their reusable components for the benefit of the community and their future projects. This initiative encourages innovation and creativity while maintaining high coding standards and ensuring reusability.

Task: Add unique reusable Rating Component and its page. Example has already been implemented. Just need to follow along and add your own creative elements. Refer to Contributing.md for detailed instructions.

Example
![Screenshot (1)](https://github.com/user-attachments/assets/9ebd1a09-3a16-4838-bcd6-4f964574809e)

**Comment by dtd0103** [comment]
Can I contribute to this issue?

**Comment by hasin-zaman** [comment]
@dtd0103 Thanks for your interest. Sure I have assigned it to you. Refer to Contributing.md to follow along example and ask away anything if you get stuck.

**Comment by dtd0103** [comment]
I have created a pull request to your branch. Please check it and give me your feedback. Thank you!
