### ISSUE TITLE
Add Unique Reusable Component

### ISSUE THREAD

**Issue by hasin-zaman** [hasin-zaman/UIlex#32]
UIlex is a community-driven platform where developers can share their reusable components for the benefit of the community and their future projects. This initiative encourages innovation and creativity while maintaining high coding standards and ensuring reusability.

Task: Add any unique reusable Component and its page. Example has already been implemented. Just need to follow along and add your own creative elements. Refer to Contributing.md for detailed instructions.

Example
![Screenshot (1)](https://github.com/user-attachments/assets/9ebd1a09-3a16-4838-bcd6-4f964574809e)

**Comment by Govindggupta** [comment]
Hey! I want to add navbar component into this project which can be really useful, Is it fine for this project?

**Comment by hasin-zaman** [comment]
@Govindggupta Yes its absolutely fine. You can refer to Contributing.md for detailed instructions to add a component. Make sure to fit navbar inside the component space only. Happy Coding!
