### ISSUE TITLE
Add Unique Reusable Avatar Component

### ISSUE THREAD

**Issue by hasin-zaman** [hasin-zaman/UIlex#4]
UIlex is a community-driven platform where developers can share their reusable components for the benefit of the community and their future projects. This initiative encourages innovation and creativity while maintaining high coding standards and ensuring reusability.

Task: Add unique reusable Avatar Component and its page. Example has already been implemented. Just need to follow along and add your own creative elements. Refer to Contributing.md for detailed instructions.

Example
![Screenshot (1)](https://github.com/user-attachments/assets/9ebd1a09-3a16-4838-bcd6-4f964574809e)

**Comment by naguib-med** [comment]
Hello ! Could you please assign me this issue? Thank you!

**Comment by hasin-zaman** [comment]
Hi @naguib-med ! I have assigned you the issue.

**Comment by naguib-med** [comment]
Hi @hasin-zaman, I’ve submitted a pull request to address this issue: #27
